### ISSUE TITLE
Missing prefab

### ISSUE THREAD

**Issue by thorikawa** [supertask/4DVFXProject#3]
I wanted to try it out on my PC, so I cloned the repo, added the depthkit packge and opened it, but some of the Prefabs are missing. For example, when I open the `AriarayRaw` scene, the Prefab with GUID `db15aa5b226605b4e9caedbe87d7d795` is missing as shown below. I thought it might be a variant prefab that was added by you, but could you please confirm?
<img width="481" alt="Screen Shot 2022-02-01 at 13 27 54" src="https://user-images.githubusercontent.com/108989/151913212-305925a8-14fa-4253-b001-354cdc70a247.png">

**Comment by supertask** [comment]
@thorikawa Thank you for your report. This might be late for you. However I've just added some ignored files which will include the missing prefab.

[472f4c5c195e80fee8a37e74336a84f9e0b287d5 ](https://github.com/supertask/4DVFXProject/commit/472f4c5c195e80fee8a37e74336a84f9e0b287d5)
